### ISSUE TITLE
Git stuff does not work for me

### ISSUE THREAD

**Issue by PaulMansour** [the-carlisle-group/AcreTools#1]
I would think it would just work if you have GitHub desktop installed. No?

**Comment by norberturkiewicz** [comment]
Not anymore.  Recent Github Desktop releases have git compiled directly
into the app.   You’ll need to download git command line tools.

**Comment by norberturkiewicz** [comment]
https://git-scm.com/downloads

**Comment by norberturkiewicz** [comment]
Fixed by installing git cmd utilities
