### ISSUE TITLE
Missing RunTests user command

### ISSUE THREAD

**Issue by rikedyp** [the-carlisle-group/AcreTools#112]
```
      ]DADO.Version
0.0.90
      ]DADO.RunTests
* Invalid user command; to see a list of all user commands type
      ] -?
```
Installed Dado Application from [Releases page](https://github.com/the-carlisle-group/Dado/releases/tag/0.0.90)
https://github.com/the-carlisle-group/Dado/wiki/Command-Reference#runtests

**Comment by PaulMansour** [comment]
Yes, sorry about that. About 7 commits were stacked up, waiting release.  A new release 0.091 is  now available.

**Comment by rikedyp** [comment]
I now have `]DADO.RunTests`, but get a `SYNTAX ERROR` when running tests because the project space doesn't seem to be found:

```
      ]DADO.OpenProject g/XL2APL
Please wait - Reading 48 files from .../g/XL2APL
Current branch: master
#.XL2APL

      ]DADO.ShowProjects
 Project  Branch  UC  CC 
 -------  ------  --  -- 
 XL2APL   master   1   0 

      ]DADO.RunTests
SYNTAX ERROR
RunTests[3] f←'T'p.Tests.⎕NL-3
                 ∧
      
```

**Comment by PaulMansour** [comment]
Are you in the project space? Most Dado commands require that you are in (or under) the project space, so it knows what project to operate on. This one in particular is not giving an appropriate message.

**Comment by rikedyp** [comment]
Oh no, I was in `#`. Indeed it works if I `⎕CS` into `#.XL2APL`.
Can you add a note to that effect in https://github.com/the-carlisle-group/Dado/wiki/Command-Reference#runtests?

**Comment by PaulMansour** [comment]
Will do.
