### ISSUE TITLE
BuildWorkspace []OFF should use error exit codes starting with 12 not 10

### ISSUE THREAD

**Issue by norberturkiewicz** [the-carlisle-group/AcreTools#62]
```~apl
 BuildWorkspace←{
     ⍺←0
     v←⍵
     pf←GetProjectFolder ⍺
     q←{'''',⍵,''''}
     l←⊂']Dado.Version'
     ⍝ Once saving from ⎕SE works, we can simply do:
     ⍝ l,←⊂'rc em←',(q pf),' ⎕SE.Dado.BuildWorkspace_ ', qv
     l,←⊂'rc em←',(q pf),' (⎕NS ⎕SE.zApps.Dado.Dado).Main.BuildWorkspace_ ',q v
     l,←⊂'em'
     **l,←⊂'⎕OFF (10+rc)'**
     ExecuteAPL l
 }
```

Dyalog default exit codes 17.1

0 | Successful ⎕OFF, )OFF, )CONTINUE, graphical exit from GUI
-- | --
1 | APL failed to start. This will occur if there was a failure  to read a translate file, there is insufficient memory, or a critical parameter  is incorrectly specified or missing.
2 | APL was terminated by SIGHUP or SIGTERM (UNIX) or in  response to a QUIT WINDOWS request. APL has done a clean exit.
3 | APL issued a syserror.
4 | Runtime violation. This occurs if a runtime application  attempts to read input from the Session. Only a development version has a  Session.
5 | APL was unable to load the Conga libraries (14.1.25383  onwards). In 16.0 the RIDE libraries have been included in the Conga  libraries.
6 | RIDE_INIT or one of its components was ill-defined, or APL was unable to use the  port, and/or unable to resolve the hostname (14.1.25383 onwards)
7 | Reserved
8 | Windows rejected APL's request to create a session window (in  earlier versions this generated a syserror 126)
9 | Dyalog has encountered a Microsoft Windows-related error when  starting and is unable to continue. For example it cannot register clipboard  formats.
10 | CEF sub-process crash - something has gone unexpectedly wrong  with either the HTMLRenderer or CEF sub-processes and cannot continue
11 | Cannot create c-stack (macOS only)

**Comment by PaulMansour** [comment]
Maybe I should got to 100? These are newly added codes.

**Comment by norberturkiewicz** [comment]
I don't understand the error trapping buy maybe mimic the unix behavior of dyalog?

Under UNIX exit codes greater than 127 indicates (127+signal number) of the untrapped signal which caused the process to terminate.
