### ISSUE TITLE
Create gitattributes file on CreateProject

### ISSUE THREAD

**Issue by JoshDavid** [the-carlisle-group/AcreTools#88]
On CreateProject, the gitattributes file should also be created recognizing APL as a language.

Could have it right after 
`_←p WriteGitIgnore ''`
**`_←p WriteGitAttributes ''`**

WriteGitAttributes would look very similar to WriteGitIgnore, the only difference is the text written and the filename. Hence, it might be better to refactor as one 'WriteGitFile' function that takes 'attributes' or 'ignore' and then the text to insert.

The important line to add would be 
`*.apl? linguist-language=APL`

N.B. This may be a "temporary" solution, so you may decide that it's not worth adding. Ideally GitHub will recognize .apl* files as being APL source code (see https://github.com/Dyalog/link/issues/52 for context). I'm just not sure when that will happen.

**Comment by PaulMansour** [comment]
Yes, I've been doing this manually. Will put it.

**Comment by PaulMansour** [comment]
Done
