### ISSUE TITLE
Format of acre.config

### ISSUE THREAD

**Issue by PaulMansour** [the-carlisle-group/AcreTools#9]
AcreTools assumes acre.config is formatted as :Namespace...:EndNamespace, asnd does not handle APLAN or JSON. It needs to handle all three.

**Comment by e9gille** [comment]
I still feel it is unnecessarily complicating matters that the config file can be any of 3 formats. Could we please reduce this to one format only? I think last time it came up @PhilLast said APLAN is his preference while @norberturkiewicz and I said JSON. I'd rather just have APLAN than all 3.
